version: '3'

includes:
  common: ./build/Taskfile.yml
  windows: ./build/windows/Taskfile.yml
  darwin: ./build/darwin/Taskfile.yml
  linux: ./build/linux/Taskfile.yml
  # iOS and Android are optional - only include if needed
  # ios: ./build/ios/Taskfile.yml
  # android: ./build/android/Taskfile.yml

vars:
  APP_NAME: "MrRSS"
  BIN_DIR: "build/bin"
  VITE_PORT: '{{.WAILS_VITE_PORT | default 5173}}'

tasks:
  build:
    summary: Builds the application
    cmds:
      - task: "{{OS}}:build"

  package:
    summary: Packages a production build of the application
    cmds:
      - task: "{{OS}}:package"

  run:
    summary: Runs the application
    cmds:
      - task: "{{OS}}:run"

  dev:
    summary: Runs the application in development mode
    cmds:
      - wails3 dev -config ./build/config.yml -port {{.VITE_PORT}}

  setup:docker:
    summary: Builds Docker image for cross-compilation (~800MB download)
    cmds:
      - task: common:setup:docker

  build:server:
    summary: Builds the server version using Docker
    cmds:
      - task: "{{OS}}:build:server"

  docker:build:server:
    summary: Builds the server version Docker image
    cmds:
      - docker build -f Dockerfile.server -t mrrss-server:latest .

  docker:run:server:
    summary: Runs the server version in Docker
    cmds:
      - docker run -p 1234:1234 -v {{.PWD}}/data:/app/data mrrss-server:latest
